workflows:
  ios-release:
    name: FreshKeep iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.freshpick.freshkeep"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Verify Firebase GoogleService-Info.plist exists
        script: |
          if [ -f "$CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found in repo"
          else
            echo "❌ GoogleService-Info.plist NOT found"
            exit 1
          fi

      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --repo-update

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dantevc854@gmail.com
        notify:
          success: true
          failure: true

  android-release:
    name: FreshKeep Android Release
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.freshpick.freshkeep"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - dantevc854@gmail.com
        notify:
          success: true
          failure: true
