workflows:
  ios-release:
    name: FreshKeep iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable      # Always use latest stable Flutter
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.freshpick.freshkeep"
      groups:
        - firebase_credentials  # Must contain GOOGLE_SERVICES_PLIST (base64 encoded)

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set up Firebase GoogleService-Info.plist
        script: |
          mkdir -p $CM_BUILD_DIR/ios/Runner
          echo $GOOGLE_SERVICES_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --repo-update

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dantevc854@gmail.com
        notify:
          success: true
          failure: true

  android-release:
    name: FreshKeep Android Release
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      flutter: stable      # Always use latest stable Flutter
      vars:
        PACKAGE_NAME: "com.freshpick.freshkeep"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - dantevc854@gmail.com
        notify:
          success: true
          failure: true
